apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-reverseproxy
  name: udagram-reverseproxy-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/udagram-reverseproxy-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-reverseproxy
